# Generated by Django 6.1 on 2026-08-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_recurringexpense_recurringexpenseshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="is_variable",
            field=models.BooleanField(default=False),
        ),
    ]
