# Generated by Django 6.1 on 2026-08-19 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0007_alter_transaction_transaction_date_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="budget_month",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
