# Generated by Django 6.1 on 2026-08-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0008_transaction_budget_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_income",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
