# Generated by Django 6.1 on 2026-08-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0019_rename_total_amount_monthlyforecast_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyforecast",
            name="recurring_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecast_overrides",
                to="budget.recurringexpense",
                verbose_name="Charge fixe (Exception mensuelle)",
            ),
        ),
    ]
