# Generated by Django 5.2.17 on 2026-09-18 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0030_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyforecast',
            name='transaction_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_transactions', to='budget.bankaccount', verbose_name='Compte ciblé (Optionnel)'),
        ),
    ]
