# Generated by Django 5.2.18 on 2026-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_monthlyforecast_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='default_bank_account',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_joint',
            field=models.BooleanField(default=False, help_text='Cochez si ce compte est co-détenu par le foyer.', verbose_name='Compte joint'),
        ),
    ]
