# Generated by Django 5.2.18 on 2026-10-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0032_remove_category_default_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlyforecast',
            name='unique_monthly_category_forecast_per_member',
        ),
    ]
