repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: ^\.devcontainer/
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.35.2
    hooks:
      - id: djlint-django
        args: ["--reformat"]

  - repo: local
    hooks:
      - id: python-check
        name: Control Python Syntax
        entry: python3 -m py_compile
        language: system
        types: [python]
