# Generated by Django 6.1 on 2026-08-19 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobalSettings",
        ),
    ]
